// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjWsvHAh9gMhsbwtB1viKF1n16XD2Q608',
    appId: '1:1073162142992:android:8620d5046438de280b9195',
    messagingSenderId: '1073162142992',
    projectId: 'gpsmapcamera-7f97e',
    storageBucket: 'gpsmapcamera-7f97e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_V8KveB5s2c34ZzlCX8X648gZbHeBOo',
    appId: '1:1073162142992:ios:2feec31176e000bf0b9195',
    messagingSenderId: '1073162142992',
    projectId: 'gpsmapcamera-7f97e',
    storageBucket: 'gpsmapcamera-7f97e.firebasestorage.app',
    iosClientId: '1073162142992-25udea0kbcsjksos8cr8ohvop6ae3fp4.apps.googleusercontent.com',
    iosBundleId: 'com.gps.gpsMapCamera',
  );
}
